# Introduction to NumPy

In [1]:
import numpy as np

## Arrays

A NumPy array is a collection of values *of the same type*, arranged along one or more dimensions, and indexed by a tuple of non-negative integers.

### One-dimensional arrays (vectors)

In [2]:
a = np.array([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(a)

[ 0  1  1  2  3  5  8 13 21 34]


In [3]:
a.shape

(10,)

In [4]:
a.dtype

dtype('int64')

In [5]:
a[3]

2

In [6]:
a[3] = 10
print(a)

[ 0  1  1 10  3  5  8 13 21 34]


### Two-dimensional arrays (matrices)

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
b.shape

(2, 3)

In [9]:
b.dtype

dtype('float64')

In [10]:
b[1, 0]

4.0

In [11]:
b[1, 0] = 10
print(b)

[[ 1.  2.  3.]
 [10.  5.  6.]]


## Slicing and indexing

### Slicing

NumPy arrays can be sliced using a syntax similar to the one used for Python lists.

In [12]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
b = a[1:, 1::2]
print(b)

[[ 6  8]
 [10 12]]


In [14]:
b[0, 0] = 100  # b[0, 0] is the same as a[1, 1]
print(a)
print(b)

[[  1   2   3   4]
 [  5 100   7   8]
 [  9  10  11  12]]
[[100   8]
 [ 10  12]]


### Integer indexing

Specific elements of a NumPy array can be accessed using lists of integer indices.

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
a[[0, 2], [1, 2]]

array([ 2, 11])

### Boolean indexing

Alternatively, elements that satisfy certain logical conditions can be selected using Boolean arrays.

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
a > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

## Functions that create arrays

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.full((3, 5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [24]:
np.random.random((3, 5))

array([[0.0751606 , 0.81010166, 0.65348123, 0.68226173, 0.25372004],
       [0.06240587, 0.5119275 , 0.52678597, 0.68651443, 0.95646157],
       [0.68692435, 0.64210692, 0.72141605, 0.47579793, 0.86665789]])

## Array operators

Basic mathematical operators such as `+` and `*` operate _element-wise_ on NumPy arrays.

In [25]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


In [27]:
3*a + b**2

array([19, 31, 45])

## Other array functions

Most functions defined in NumPy operate on arrays.

In [28]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
np.sum(a)

78

In [30]:
np.mean(a)

6.5

In [31]:
np.sum(a, axis=0)

array([15, 18, 21, 24])

In [32]:
np.sum(a, axis=1)

array([10, 26, 42])

## Broadcasting

Broadcasting allows NumPy to operate on arrays of different shapes when performing some operation.

This is particularly useful when we want to use a smaller array multiple times to perform some operation on a larger array.

In [33]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
b = np.arange(a.shape[1])
print(b)

[0 1 2 3]


In [35]:
a - b

array([[1, 1, 1, 1],
       [5, 5, 5, 5],
       [9, 9, 9, 9]])

In [36]:
b = np.arange(a.shape[0])
print(b)

[0 1 2]


In [37]:
b[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [38]:
a - b[:, np.newaxis]

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])